"""add_is_active_to_workflows

Revision ID: 699f097bd3d3
Revises: fe808d3d4412
Create Date: 2026-07-04 01:57:22.917123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699f097bd3d3'
down_revision: Union[str, Sequence[str], None] = 'fe808d3d4412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'is_active')
    # ### end Alembic commands ###
