"""add retry_count, next_retry_at and last_error columns to ActionExecution model

Revision ID: d4e8c24521e1
Revises: f36d397b1dad
Create Date: 2026-07-13 14:37:35.258359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e8c24521e1'
down_revision: Union[str, Sequence[str], None] = 'f36d397b1dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("""
            ALTER TYPE executionstatusenum
            ADD VALUE IF NOT EXISTS 'dead_letter';
        """)

    op.add_column('action_executions', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('action_executions', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('action_executions', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_executions', 'last_error')
    op.drop_column('action_executions', 'next_retry_at')
    op.drop_column('action_executions', 'retry_count')
    # ### end Alembic commands ###
